m2e-code-quality/m2e-code-quality

- com.basistech.m2e.code.quality.findbugs/src/main/java/com/basistech/m2e/code/quality/findbugs/EclipseFindbugsProjectConfigurator.java
- mars/mars.target
Disable adding FindBugs nature when the project type is not Java.
> FindBugs nature only for Java project

- com.basistech.m2e.code.quality.checkstyle/src/main/java/com/basistech/m2e/code/quality/checkstyle/MavenPluginConfigurationTranslator.java
but rather under .metadata/.plugins/...
Fixes #54 and #71 - replaces pr #55
Basically the same like pr #55 , but just  against develop branch.
> Store checkstyle-header and checktyle-suppressions files not under target/

- README.md
Signed-off-by: Anton Johansson <antoon.johansson@gmail.com>
> Fixed incorrect reference and change to a link

- README.md
feel free to rephrase this differently .. how do you use Oomph? Do you drag & drop the .setup somehow? Just give the Eclipse Installer the URL directly - how do you do that?
> Document m2e-code-quality.setup

- com.basistech.m2e.code.quality.checkstyle/META-INF/MANIFEST.MF
- com.basistech.m2e.code.quality.findbugs/META-INF/MANIFEST.MF
- com.basistech.m2e.code.quality.pmd/META-INF/MANIFEST.MF
- com.basistech.m2e.code.quality.shared/META-INF/MANIFEST.MF
- neon/neon.target
- neon/pom.xml
- oxygen/oxygen.target
- oxygen/pom.xml
- pom.xml
See 
I think this may fix issues #100, #102, but I haven't tested it. First PR ever.
> Try to fix working with Eclipse 4.6 (Neon), 4.7 (Oxygen).

- com.basistech.m2e.code.quality.pmd/src/main/java/com/basistech/m2e/code/quality/pmd/EclipsePmdProjectConfigurator.java
> Adapt to PMD RuleSetFactory API changes

- .travis.yml
- pom.xml
> ditch multiple Taret Platform build (and deploy..) from Travis CI

- com.basistech.m2e.code.quality.checkstyle/META-INF/MANIFEST.MF
- com.basistech.m2e.code.quality.findbugs/META-INF/MANIFEST.MF
- com.basistech.m2e.code.quality.pmd/META-INF/MANIFEST.MF
- com.basistech.m2e.code.quality.shared/META-INF/MANIFEST.MF
@ArloL would you be willing to merge this to address https://github.com/m2e-code-quality/m2e-code-quality/issues/114 ?
> #114: remove M2E <= 1.8.x contraint from MANIFEST.MF

- com.basistech.m2e.code.quality.checkstyle/src/main/java/com/basistech/m2e/code/quality/checkstyle/MavenPluginConfigurationTranslator.java
- com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/AbstractMavenPluginConfigurationTranslator.java
This is an alternative to #108
> Sanitize filenames derived from executionIds

- com.basistech.m2e.code.quality.checkstyle/src/main/java/com/basistech/m2e/code/quality/checkstyle/MavenPluginConfigurationTranslator.java
Closes #150 
This was much simpler than what I expected.
I verified if there were other case like that but there were not :)
> Do not fail if no suppressions are configured in Checkstyle

- pom.xml
see https://github.com//dependabot-core/issues/671 for full background
> remove un-used (and long gone with the wind) maven-osgi-lifecycle-plugin

- index.html
for full background,
see also https://github.com/m2e-code-quality/m2e-code-quality/issues/123
and https://github.com/m2e-code-quality/m2e-code-quality/issues/124
and https://github.com/m2e-code-quality/m2e-code-quality/issues/143
> Change home page to point to new p2 repo, and drop individual names to make it more of an open community

- com.basistech.m2e.code.quality.pmd/src/main/java/com/basistech/m2e/code/quality/pmd/EclipsePmdProjectConfigurator.java
- com.basistech.m2e.code.quality.pmd/src/main/java/com/basistech/m2e/code/quality/pmd/MavenPluginConfigurationTranslator.java
- com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/AbstractMavenPluginConfigurationTranslator.java
This one was a bit more complicated, as there are two Executions (check and forked pmd). The skip needs to be checked on the "check" execution, other config is read from "pmd".
> Support <skip> configuration for PMD, too

- .editorconfig
- com.basistech.m2e.code.quality.checkstyle/src/main/java/com/basistech/m2e/code/quality/checkstyle/MavenPluginConfigurationTranslator.java
add .editorconfig root config file, see https://editorconfig.org
> Use EditorConfig to standardize formatting

- com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/EclipseConfigManager.java
Prevents triggering builds when there's no actual change
> Prevent project update when no nature is to be removed

- .travis.yml
- com.basistech.m2e.code.quality.checkstyle.test/pom.xml
- com.basistech.m2e.code.quality.findbugs.test/pom.xml
- com.basistech.m2e.code.quality.spotbugs.test/pom.xml
Run all tests in travis builds
> Run tests in travis

- com.basistech.m2e.code.quality.checkstyle.test/META-INF/MANIFEST.MF
- com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-check/README.markdown
- com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-check/pom.xml
- com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-check/src/main/java/cat/App.java
- com.basistech.m2e.code.quality.checkstyle.test/src/main/java/com/basistech/m2e/code/quality/checkstyle/test/EclipseCheckstyleProjectConfigurationTest.java
> Testcase for Checkstyle

- com.basistech.m2e.code.quality.checkstyle/src/main/java/com/basistech/m2e/code/quality/checkstyle/EclipseCheckstyleProjectConfigurator.java
@erwint this fixes #180 which you broke in #172 
Would you happen to have any more motivation than I do right now to follow-up with a test for this? :smiling_imp:
> do not break while applying all Checkstyle executions (fixes #180)

- com.basistech.m2e.code.quality.pmd/src/main/java/com/basistech/m2e/code/quality/pmd/MavenPluginConfigurationTranslator.java
all rights granted -- Alexander Lehmann
> Fixes #196

- com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-check/pom.xml
- com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-multi-check/pom.xml
> Add explicit checkstyle version in test projects

- com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-multi-check/pom.xml
- com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-multi-module/README.markdown
- com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-multi-module/checks/checkstyle_config.xml
- com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-multi-module/module1/pom.xml
- com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-multi-module/module1/src/main/java/bug/demo/BugDemoMain.java
- com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-multi-module/pom.xml
- com.basistech.m2e.code.quality.checkstyle.test/src/main/java/com/basistech/m2e/code/quality/checkstyle/test/EclipseCheckstyleProjectConfigurationTest.java
- com.basistech.m2e.code.quality.shared.test/src/main/java/com/basistech/m2e/code/quality/shared/test/AbstractMavenProjectConfiguratorTestCase.java
- com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/AbstractMavenPluginConfigurationTranslator.java
> ResourceResolver - search up the maven project parent hierarchy

- com.basistech.m2e.code.quality.pmd.test/projects/pmd-custom-ruleset/README.markdown
- com.basistech.m2e.code.quality.pmd.test/projects/pmd-custom-ruleset/custom-ruleset.xml
- com.basistech.m2e.code.quality.pmd.test/projects/pmd-custom-ruleset/pom.xml
- com.basistech.m2e.code.quality.pmd.test/projects/pmd-custom-ruleset/src/main/java/cat/App.java
- com.basistech.m2e.code.quality.pmd.test/src/main/java/com/basistech/m2e/code/quality/pmd/tests/EclipsePmdProjectConfigurationTest.java
- com.basistech.m2e.code.quality.pmd/src/main/java/com/basistech/m2e/code/quality/pmd/EclipsePmdProjectConfigurator.java
> Fix IndexOutOfBoundsException when loading ruleset

- com.basistech.m2e.code.quality.spotbugs/src/main/java/com/basistech/m2e/code/quality/spotbugs/EclipseSpotbugsProjectConfigurator.java
This reverts commit f6195acf23f750a8dac3b1cafcbd1128f5bbef31.
See comment https://github.com/m2e-code-quality/m2e-code-quality/pull/343#issuecomment-2057469516 for the reason.
> Revert "[spotbugs] Add in 'verify' as a valid goal (#343)"
