com.basistech.m2e.code.quality.checkstyle/META-INF/MANIFEST.MF

The current develop branch doesn't build -> https://travis-ci.org/m2e-code-quality/m2e-code-quality/builds/81722940
This PR should fix it...

Add import for org.apache.commons.lang to use StringEscapeUtils

---

test-projects/failing-checkstyle-example/build-tools/pom.xml
test-projects/failing-checkstyle-example/build-tools/src/main/resources/PMDRules.xml
test-projects/failing-checkstyle-example/build-tools/src/main/resources/checkstyle-suppressions.xml
test-projects/failing-checkstyle-example/build-tools/src/main/resources/checkstyle.properties
test-projects/failing-checkstyle-example/build-tools/src/main/resources/checkstyle.xml
test-projects/failing-checkstyle-example/failing-checkstyle-example-core/pom.xml
test-projects/failing-checkstyle-example/failing-checkstyle-example-persistence/pom.xml
test-projects/failing-checkstyle-example/pom.xml

Hi there,
I've added a Maven multi module project with a build-tools module with short configurations for PMD and Checkstyle in test-projects/failing-checkstyle-example.
When I import the project with "import existing maven projects" in Eclipse Mars the pmd configuration is generated, but not the checkstyle configuration.
regards,
Martin

initial checkin of m2e cs example

---

com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/ResourceResolver.java

This creates a log entry for the problem in https://github.com/m2e-code-quality/m2e-code-quality/issues/83.
This does not "solve" https://github.com/m2e-code-quality/m2e-code-quality/issues/83, but could still be useful to others in the future hitting similar problems.
It would be MUCH better if these warn logs would also show up in the Eclipse Error View, and not just in the log file as it does with my naive use of slf4j - but I do not know the correct logging API to use in M2E related code for that - do you?

Log warning if ambigous classpath resource location

---

com.basistech.m2e.code.quality.site/associate-sites.xml
m2e-code-quality.setup
mars/mars.target
neon/neon.target
oxygen/oxygen.target
pom.xml

This uses the new update site of pmd-eclipse-plugin: https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/
Without this change, I cannot build m2e-code-quality anymore... seems like the sourceforge mirrors return invalid SSL certs regarding the hostnames...

Use new pmd-eclipse-plugin update site

---

com.basistech.m2e.code.quality.findbugs/src/main/java/com/basistech/m2e/code/quality/findbugs/EclipseFindbugsProjectConfigurator.java
com.basistech.m2e.code.quality.findbugs/src/main/java/com/basistech/m2e/code/quality/findbugs/FindbugsEclipseConstants.java
com.basistech.m2e.code.quality.findbugs/src/main/java/com/basistech/m2e/code/quality/findbugs/MavenPluginConfigurationTranslator.java
com.basistech.m2e.code.quality.spotbugs/src/main/java/com/basistech/m2e/code/quality/spotbugs/EclipseSpotbugsProjectConfigurator.java
com.basistech.m2e.code.quality.spotbugs/src/main/java/com/basistech/m2e/code/quality/spotbugs/MavenPluginConfigurationTranslator.java
com.basistech.m2e.code.quality.spotbugs/src/main/java/com/basistech/m2e/code/quality/spotbugs/SpotbugsEclipseConstants.java

This allows the user to specify whether Findbugs/Spotbugs is run during each build or just on demand (the `<skip>` can be put in a profile that is set for m2e only).

Support <skip> configuration for findbugs/spotbugs like for checkstyle

---

com.basistech.m2e.code.quality.checkstyle/src/main/java/com/basistech/m2e/code/quality/checkstyle/MavenPluginConfigurationTranslator.java
com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/AbstractMavenPluginConfigurationTranslator.java
com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/EclipseConfigManager.java

While optimizing a very big Eclipse workspace we noticed lots of resource changed coming from m2e-code-quality, that did not actually change any file's content. As every resource change triggers an Auto-Build this is quite expensive. Instead, we check before writing if there's an actual change in the contents.

Do not touch files if not needed

---

com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/AbstractMavenPluginProjectConfigurator.java

In big workspaces we noticed strange classloading errors in Eclipse, which result from Mojo instantiated for the ResourceResolver. As the Mojo instance is not needed at all (just it's classpath), we changed it to not actually create instances of the Mojo. Unfortunately, some internal m2e API is needed for this.

Just get a classloader for the Mojo, no need for an actual instance

---

m2e-code-quality.setup
photon/photon.target
photon/pom.xml
pom.xml

Closes #121 
I extracted from #121 what seemed to be still relevant.
I agree with #115 that the constraint should be up to v2.
I fixed the version of the various quality control tools in the target, but let the eclipse stuffs at version `0.0.0` to always build against the latest of the Photon update site. Maybe that's a mistake, I can change that.
There is something I'm really not clear about, Eclipe build is always such a mess:
- According to #120, our current build is already compatible with Photon, so why is there a need for a specific target?
- I updated the content of the `m2e-code-quality.setup` file but I have absolutely no idea what is it for. It seems to duplicate information we can find both in the targets and in the pom.xml…
- The update sites in the pom.xml doesn't seem to …

Add Photon target

---

com.basistech.m2e.code.quality.checkstyle/src/main/java/com/basistech/m2e/code/quality/checkstyle/MavenPluginConfigurationTranslator.java

Fixes https://github.com/m2e-code-quality/m2e-code-quality/issues/117.
If Checkstyle source directories are not configured, use the project code sources as default.

To address issue #117

---

pom.xml

This is needed so that the tests can be run on 64Bit Windows, too

Tests in x86_64 on windows

---

neon/neon.target
oxygen/oxygen.target
photon/photon.target

This will prevent the build to break each time the dependent plugin is updated.

Use 0.0.0 version where there's a single version only

---

m2e-code-quality.setup

This should fix the error in #157 that ```org.eclipse.sdk.feature.group``` can't be found.

Add newer eclipse versions to oomph

---

com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-multi-check/README.markdown
com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-multi-check/pom.xml
com.basistech.m2e.code.quality.checkstyle.test/projects/checkstyle-multi-check/src/main/java/cat/App.java
com.basistech.m2e.code.quality.checkstyle.test/src/main/java/com/basistech/m2e/code/quality/checkstyle/test/EclipseCheckstyleProjectConfigurationTest.java
com.basistech.m2e.code.quality.checkstyle/src/main/java/com/basistech/m2e/code/quality/checkstyle/EclipseCheckstyleProjectConfigurator.java

This adds test for #180 and refactors the code to be better comprehensible: Nature and Builder are added if there is at least one non-skipped execution.

Refactored multiple checkstyle executions and added tests

---

com.basistech.m2e.code.quality.checkstyle.test/META-INF/MANIFEST.MF
com.basistech.m2e.code.quality.checkstyle/META-INF/MANIFEST.MF
com.basistech.m2e.code.quality.findbugs.test/META-INF/MANIFEST.MF
com.basistech.m2e.code.quality.findbugs/META-INF/MANIFEST.MF
com.basistech.m2e.code.quality.pmd/META-INF/MANIFEST.MF
com.basistech.m2e.code.quality.shared.test/META-INF/MANIFEST.MF
com.basistech.m2e.code.quality.shared/META-INF/MANIFEST.MF
com.basistech.m2e.code.quality.spotbugs.test/META-INF/MANIFEST.MF
com.basistech.m2e.code.quality.spotbugs/META-INF/MANIFEST.MF

Avoid Eclipse warnings for Java 9 compatibility by adding one more
header to each manifest.

Add Automatic-Module-Name header

---

com.basistech.m2e.code.quality.findbugs.feature/feature.properties
com.basistech.m2e.code.quality.findbugs.feature/feature.xml
com.basistech.m2e.code.quality.findbugs.feature/pom.xml
com.basistech.m2e.code.quality.findbugs.test/META-INF/MANIFEST.MF
com.basistech.m2e.code.quality.findbugs.test/pom.xml
com.basistech.m2e.code.quality.findbugs/META-INF/MANIFEST.MF
com.basistech.m2e.code.quality.findbugs/pom.xml
com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/AbstractMavenPluginConfigurationTranslator.java
com.basistech.m2e.code.quality.spotbugs.feature/pom.xml
com.basistech.m2e.code.quality.spotbugs/pom.xml

Both projects write themselves with uppercase B, therefore change this
in user visible output (e.g. feature names etc.). In contrast,
Checkstyle does not use an uppercase S.

Use uppercase B in SpotBugs/FindBugs

---

mars/mars.target
neon/neon.target
oxygen/oxygen.target
photon/photon.target

The POM repositories and the Eclipse targets are somewhat out of sync.
As a quickfix just add the missing bundle to the Eclipse target. In the
long run I suggest to use a .target file in the Maven build, too,
instead of fetching whatever is available on the repository URLs.

Fix #203: Have org.apache.commons.lang in targets

---

com.basistech.m2e.code.quality.findbugs/src/main/java/com/basistech/m2e/code/quality/findbugs/MavenPluginConfigurationTranslator.java
com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/AbstractMavenPluginConfigurationTranslator.java
com.basistech.m2e.code.quality.spotbugs/src/main/java/com/basistech/m2e/code/quality/spotbugs/MavenPluginConfigurationTranslator.java

While the Maven plugin can handle a comma separated list of files and
the Eclipse plugin can also have more than one file, the configuration
did not handle this case.

Handle multiple values for include/excludeFilterFile for spot/findBugs

---

com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/AbstractMavenPluginConfigurationTranslator.java

This failure may be temporary, as it uses the plugin's classpath in the
project, so popping up an error message seems a bit too much. Also,
includes more information about the error (project an mojo)
The error logged looks like this:
`com.basistech.m2e.code.quality.shared.AbstractMavenPluginConfigurationTranslator  - my-project: could not locate resource [notThere] in classpath of [org.codehaus.mojo:findbugs-maven-plugin:3.0.3:findbugs {execution: default}]`

Log only an error if a resource file cannot be found (fixes #199)

---

com.basistech.m2e.code.quality.shared/src/main/java/com/basistech/m2e/code/quality/shared/AbstractMavenPluginProjectConfigurator.java

With m2e 1.12 the project configuration is batched, so if you use the
old and new IMavenProjectFacade to compare your memory requirements are
doubled. So as we check on unconfiguration whether any work needs to be
done at all, we can just use the new state as a precondition.

checkUnconfigurationRequired does not need old IMavenProjectFacade

---

m2e-code-quality.setup
mars/mars.target
neon/neon.target
oxygen/oxygen.target
photon/photon.target
pom.xml

The Update site of [PMD Eclipse Plugin](https://github.com/pmd/pmd-eclipse-plugin) moved from <https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/> to <https://pmd.github.io/pmd-eclipse-plugin-p2-site/>.
See also https://github.com/pmd/pmd-eclipse-plugin/issues/140.

New PMD Eclipse Plugin update site

---

neon/neon.target
oxygen/oxygen.target
photon/photon.target
pom.xml

The new checkstyle update site is https://checkstyle.org/eclipse-cs-update-site/
This PR should make the build work again.

Fix checkstyle update site

---

.github/workflows/build.yml
Gemfile
doc/release.md
tools/prepare_release.sh
tools/publish-update-site.sh
tools/release.sh

This PR adjusts the scripts to run on github actions.
The release procedure is the same as before - create and push a tag from the branch `develop`.

Release automation with github actions

---

.github/workflows/build.yml
com.basistech.m2e.code.quality.target-platform/2022-06.target
com.basistech.m2e.code.quality.target-platform/oxygen.target
pom.xml
tools/build.sh

This contains a fix, so that the oxygen target (the default target platform) works again: Eclipse Checkstyle Plugin 10 requires now at least eclipse 2019-06, which requires at least java 11 (https://checkstyle.org/eclipse-cs/#!/releasenotes)

Improve build to test multiple target platforms

---

.github/actions/setup/action.yml
.github/actions/verify/action.yml
.github/workflows/build.yml
README.md
tools/toolchains.xml

Remove java8 and java11. They are not needed anymore since we build now with Java 17 only.
Introduce two composite actions:
- setup
- verify
* Refs #292 
* Refs #294

[ci] Refactor Github Actions

---

com.basistech.m2e.code.quality.shared.test/META-INF/MANIFEST.MF
com.basistech.m2e.code.quality.shared.test/src/main/java/com/basistech/m2e/code/quality/shared/test/AbstractMavenProjectConfiguratorTestCase.java
pom.xml

This removes the manual setup of the default JVM that was required for macos builds.
I've taken the inspiration from https://github.com/eclipse-m2e/m2e-core/blob/0aa663f75337f846f35a610bfb893f9c7c07605f/pom.xml#L410-L428

Use o.e.jdt.launching.macosx for configuring the installed JDKs in tests

---

doc/github-actions.md
tools/build.sh
tools/prepare_release.sh
tools/publish-update-site.sh

Uses github-actions[bot] as commit identity
* Refs #282
* See https://github.com/orgs/community/discussions/26560 and https://api.github.com/users/github-actions[bot]

Remove usage of m2e-code-quality-bot and use github-actions[bot] instead

---

.github/actions/verify/action.yml

This gets rid of the deprecation warnings:
```
fail-fast verify (ubuntu-latest, 2022-09)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: GabrielBB/xvfb-action@v1
```

Replace GabrielBB/xvfb-action with direct xvfb-run call

---

com.basistech.m2e.code.quality.spotbugs.test/projects/exclude-bugs-file/README.markdown
com.basistech.m2e.code.quality.spotbugs.test/projects/exclude-bugs-file/baseline.xml
com.basistech.m2e.code.quality.spotbugs.test/projects/exclude-bugs-file/pom.xml
com.basistech.m2e.code.quality.spotbugs.test/projects/exclude-bugs-file/src/main/java/cat/App.java
com.basistech.m2e.code.quality.spotbugs.test/src/main/java/com/basistech/m2e/code/quality/spotbugs/tests/EclipseSpotbugsProjectConfigurationTest.java
com.basistech.m2e.code.quality.spotbugs/src/main/java/com/basistech/m2e/code/quality/spotbugs/EclipseSpotbugsProjectConfigurator.java
com.basistech.m2e.code.quality.spotbugs/src/main/java/com/basistech/m2e/code/quality/spotbugs/MavenPluginConfigurationTranslator.java
com.basistech.m2e.code.quality.spotbugs/src/main/java/com/basistech/m2e/code/quality/spotbugs/SpotbugsEclipseConstants.java

It would be good to be able to use the [`excludeBugsFile` option](https://spotbugs.github.io/spotbugs-maven-plugin/spotbugs-mojo.html#excludeBugsFile) with m2e.
This patch adds support for it (mostly adapted from code handling `excludeFilterFile`).

Add support for excludeBugsFile option for SpotBugs

---

.github/workflows/build.yml
pom.xml
target-platforms/2023-09.target
target-platforms/2023-12.target

Note: GitHub Actions will only run the latest target platform (for now 2023-12) on all os (linux, windows, macos). Then only the oldest one will be executed under linux (2022-09) - all others are not tested anymore.

Support eclipse 2023-12

---

com.basistech.m2e.code.quality.spotbugs/src/main/java/com/basistech/m2e/code/quality/spotbugs/EclipseSpotbugsProjectConfigurator.java

'verify' goal was added to maven project a long time ago.  I don't see any tests at all for spotbugs nor pmd, so I just aimed for getting the newer goal to be available here.
See https://github.com/search?q=repo%3Aspotbugs%2Fspotbugs-maven-plugin+%40Mojo&type=code
I didn't bother with 'gui' although that could be ran from Eclipse but typically would not.
Spotbugs verify mojo: https://spotbugs.github.io/spotbugs-maven-plugin/verify-mojo.html
Description of this goal, see https://github.com/spotbugs/spotbugs-maven-plugin/blob/master/src/main/groovy/org/codehaus/mojo/spotbugs/VerifyMojo.groovy

[spotbugs] Add in 'verify' as a valid goal

---

.github/workflows/build.yml
pom.xml
target-platforms/2024-03.target

- 2024-03 is built and tested by default on all operating systems
- 2022-09 is the oldest one, that is built and tested on linux only
- all other versions might or might not work

Support eclipse 2024-03
